### ISSUE TITLE
SimpleMarketplace.sol is  rejected by Blockchain Workbench

### ISSUE THREAD

**Issue by amrikmahal** [Azure-Samples/blockchain#203] opened 2019-10-02 16:00 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Download SimpleMarketplace.sol from [https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/application-and-smart-contract-samples/simple-marketplace/ethereum/SimpleMarketplace.sol]

Try to upload the sample smart contract in Azure Workbench to create a new application.

### Any log messages given by the failure
>We found these errors in your contract code. Resolve them and upload the file again.

{"Errors":["Workflow contract SimpleMarketplace should not derive from WorkbenchBase base contract. This is considered an error now. Update the SimpleMarketplace contract to remove WorkbenchBase and calls to \"ContractCreated\" and \"ContractUpdated\" functions. "],"Warnings":[]}

### Expected/desired behavior
> sucessfull creation of sample application. 
![workbench error](https://user-images.githubusercontent.com/17153208/66060703-bbf9b680-e55b-11e9-8d52-a2fd070b043c.JPG)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10 with Chrome
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ramyapradhan** [comment] 2019-10-07 23:46
Greetings,

Thank you for your message.  I have not been able to reproduce the error with the existing application and on the latest version of Workbench.  

It looks like you may be having an older version of the SimpleMarketplace application because the one in the link, which is also the current one, does not have Workbench base nor the function calls.  Please try with the latest versions and let us know how that goes.

Thanks.

**Comment by ramyapradhan** [comment] 2020-01-22 22:30
Hello @amrikmahal, I am writing to check in with you and see if you are unblocked.  Please let me know if we can help you in any way.  Thanks!

**Comment by ramyapradhan** [comment] 2020-02-13 22:37
Hello @amrikmahal,

I am writing to inform you that I will be closing this issue since it has been open for more than 30 days.  Please feel free to re-open it if required.

Thanks,
Ramya

**Closed by ramyapradhan** 2020-02-13 22:37 UTC
